spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/vea?useUnicode=true&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&nullNamePatternMatchesAll=true&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&autoReconnect=true&useSSL=false&pinGlobalTxToPhysicalConnection=true
    username: root
    password: root
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
kernel:
  file:
    ftp:
      enabled: true
      domain: http://127.0.0.1:88
      host: 127.0.0.1
      port: 21
      auth: true
      user-name: hanftp
      password: hanlions2017
      is-passive: true
      temp-dir: /home/ftp_tmp
      prefix: develop
system:
  user-icon: